# network
host: '0.0.0.0'
port: 5566

# map
map_file: '/mnt/c/Users/user/Documents/GitHub/brainhack22_robotics/data/maps/map_complex_1cm.png'
map_scale: 0.01

# display
robot_radius: 10

# simulation
start_pose:
  x: 0.2
  y: 0.2
  z: 0.0
use_noisy_pose: off
robot_phy_length: 0.32
pos_noise_stddev: 0.05

# localization proxy
proxy_real_robot: off
proxy_host: 'localhost'
proxy_port: 5566

# logging
log_level: 'debug'

# clues
clues:
  - clue_id: 2
    trigger:
      x: 0.2
      y: 0.2
      r: 0.5
    location:
      x: 4.0
      y: 0.2
    audio_file: '/mntc/Users/user/Documents/GitHub/brainhack22_robotics/data/audio/SM4_F48_A0100.wav'

# targets
targets:
  - target_id: 1
    trigger:
      x: 3.7
      y: 0.3
      r: 0.2
    image_file: '<some_image_file>'